# Console RTT
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
CONFIG_CBPRINTF_FP_SUPPORT=y

# LED driver
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

# Buzzer driver
CONFIG_PWM=y

# Clicker board hts221 driver
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_HTS221=y

# Clicker board MCP2515 CAN driver
CONFIG_CAN=y

# Modem
CONFIG_NRF_MODEM_LIB=y
CONFIG_LTE_LINK_CONTROL=y

# GNSS
CONFIG_LTE_NETWORK_MODE_LTE_M_GPS=y
CONFIG_LTE_NETWORK_MODE_NBIOT_GPS=n
CONFIG_LTE_NETWORK_MODE_LTE_M_NBIOT_GPS=n
CONFIG_MODEM_ANTENNA=y
CONFIG_MODEM_ANTENNA_GNSS_EXTERNAL=y

# Tests
CONFIG_SEVEN_TEST_LED=n
CONFIG_SEVEN_TEST_BUZZER=n
CONFIG_SEVEN_TEST_I2C_MIKROBUS=n
CONFIG_SEVEN_TEST_CAN_MIKROBUS=n
CONFIG_SEVEN_TEST_GNSS=n
CONFIG_SEVEN_TEST_LTE=n
