# Console RTT
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n

# LED driver
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

# Buzzer driver
CONFIG_PWM=y
